### PR TITLE
Added support of displaying class member collections

### PR DESCRIPTION
**Pull request by stbychkov**
Hi,

[There](https://github.com/Burgyn/MMLib.ToString/issues/2) is a related issue for this PR.

### CODE REVIEW

**Review by Burgyn — APPROVED** [review]

**Comment by Burgyn** [comment]
Hi @stbychkov,

thanks for your PR. Please fix dotnet version in workflows.

Thanks.

**Comment by stbychkov** [comment]
It's fixed and ready to merge

**Comment by Burgyn** [comment]
PR pipeline still failed. Please fix it.

**Comment by stbychkov** [comment]
It seems that `Demo` project still references to `1.0.1` version. Should I change the reference to the local project? Because PR workflow must go before the deployment, so I cannot just change the version to `1.1.0`

**Comment by Burgyn** [comment]
Thank you for your efforts. New version will be released soon.

**Pull request merged**
